import Head from "next/head";
import Login from "../components/Login";
import Userboard from "../components/Userboard";
import { auth } from "../firebase-config";

export default function Home() {
  return (
    <>
      <Head>
        <title>es</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!auth.currentUser ? <Login /> : <Userboard />}
    </>
  );
}
