import Head from "next/head";
import Login from "../components/Login";
import Userboard from "../components/Userboard";
import { useAuth } from "../context/AuthContext";

export default function Home() {
  const { currentUser } = useAuth();
  return (
    <>
      <Head>
        <title>TupCRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentUser ? <Userboard /> : <Login />}
    </>
  );
}
